//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ИСПП6_Вар6_Агапов_АндреевEntities1 : DbContext
    {
        public ИСПП6_Вар6_Агапов_АндреевEntities1()
            : base("name=ИСПП6_Вар6_Агапов_АндреевEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<СекретныйВопрос> СекретныйВопрос { get; set; }
        public virtual DbSet<Договоры> Договоры { get; set; }
        public virtual DbSet<ЗадачиПроекта> ЗадачиПроекта { get; set; }
        public virtual DbSet<ЗатратыПроекта> ЗатратыПроекта { get; set; }
        public virtual DbSet<ИспользованиеНедвижимости> ИспользованиеНедвижимости { get; set; }
        public virtual DbSet<ОбъектыНедвижимости> ОбъектыНедвижимости { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Проекты> Проекты { get; set; }
        public virtual DbSet<РасчетЗарплаты> РасчетЗарплаты { get; set; }
        public virtual DbSet<РесурсыПроекта> РесурсыПроекта { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Тендеры> Тендеры { get; set; }
        public virtual DbSet<УчастникиТендера> УчастникиТендера { get; set; }
        public virtual DbSet<УчетРабочегоВремени> УчетРабочегоВремени { get; set; }
    }
}
