//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договоры
    {
        public int КодДоговора { get; set; }
        public string НомерДоговора { get; set; }
        public Nullable<int> КодТендера { get; set; }
        public int КодПоставщика { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public System.DateTime ДатаОкончания { get; set; }
        public decimal ОбщаяСумма { get; set; }
        public string Статус { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual Тендеры Тендеры { get; set; }
    }
}
