//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗадачиПроекта
    {
        public int КодЗадачи { get; set; }
        public int КодПроекта { get; set; }
        public string НазваниеЗадачи { get; set; }
        public int Исполнитель { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public System.DateTime СрокВыполнения { get; set; }
        public string Статус { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Проекты Проекты { get; set; }
    }
}
