//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗатратыПроекта
    {
        public int КодЗатраты { get; set; }
        public int КодПроекта { get; set; }
        public System.DateTime Дата { get; set; }
        public string Описание { get; set; }
        public decimal Сумма { get; set; }
        public string Категория { get; set; }
    
        public virtual Проекты Проекты { get; set; }
    }
}
