//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИспользованиеНедвижимости
    {
        public int КодИспользования { get; set; }
        public int КодОбъекта { get; set; }
        public Nullable<int> КодПроекта { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public string Назначение { get; set; }
    
        public virtual ОбъектыНедвижимости ОбъектыНедвижимости { get; set; }
        public virtual Проекты Проекты { get; set; }
    }
}
