//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОбъектыНедвижимости
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ОбъектыНедвижимости()
        {
            this.ИспользованиеНедвижимости = new HashSet<ИспользованиеНедвижимости>();
        }
    
        public int КодОбъекта { get; set; }
        public string Наименование { get; set; }
        public string Адрес { get; set; }
        public string ТипНедвижимости { get; set; }
        public decimal Площадь { get; set; }
        public int Ответственный { get; set; }
        public string Статус { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИспользованиеНедвижимости> ИспользованиеНедвижимости { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
