//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проекты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проекты()
        {
            this.ЗадачиПроекта = new HashSet<ЗадачиПроекта>();
            this.ЗатратыПроекта = new HashSet<ЗатратыПроекта>();
            this.ИспользованиеНедвижимости = new HashSet<ИспользованиеНедвижимости>();
            this.РесурсыПроекта = new HashSet<РесурсыПроекта>();
        }
    
        public int КодПроекта { get; set; }
        public string НазваниеПроекта { get; set; }
        public string Описание { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаЗавершения { get; set; }
        public decimal Бюджет { get; set; }
        public int РуководительПроекта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗадачиПроекта> ЗадачиПроекта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗатратыПроекта> ЗатратыПроекта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИспользованиеНедвижимости> ИспользованиеНедвижимости { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РесурсыПроекта> РесурсыПроекта { get; set; }
    }
}
