//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class РасчетЗарплаты
    {
        public int КодРасчета { get; set; }
        public int КодСотрудника { get; set; }
        public System.DateTime Период { get; set; }
        public decimal Оклад { get; set; }
        public Nullable<decimal> Премия { get; set; }
        public Nullable<decimal> Удержания { get; set; }
        public decimal ИтогоНачислено { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
