//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class РесурсыПроекта
    {
        public int КодРесурса { get; set; }
        public int КодПроекта { get; set; }
        public string НаименованиеРесурса { get; set; }
        public string ТипРесурса { get; set; }
        public int Количество { get; set; }
        public decimal Стоимость { get; set; }
    
        public virtual Проекты Проекты { get; set; }
    }
}
